### PR TITLE
Remove static configs from Ansible

### PR DESCRIPTION
**Pull request by pallenSL**
Also use shell: to make the docker service stuff idempotent

### CODE REVIEW

**Comment by jebbinSCL** [comment]
:ship:

**Comment by niksoper** [comment]
If it works, it works... :+1:

**Comment by niksoper** [comment]
@pallenSL is this safe to merge immediately?

**Comment by pallenSL** [comment]
I'm not quite sure what you mean.
Ansible is run manually to build the boxes, so the merge itself won't do anything.

**Pull request merged**
