### PR TITLE
Adding docker compose to bring up databases only.

### PR DESCRIPTION
**Pull request by jebbinSCL**
Splitting a db only docker compose from larger system compose.

### CODE REVIEW

**Comment by pallenSL** [comment]
Can we have a README, please?  Text is fine.

I can see that this will run up MySql and DynamoDb in containers, assuming I am on a suitable VM.  But I've no idea how I could use those new dbs.

**Comment by jebbinSCL** [comment]
Readme added

**Comment by pallenSL** [comment]
:shipit:

**Comment by dmorrisSL** [comment]
:shipit:

**Pull request merged**
